include: package:lint/strict.yaml

linter:
  rules:
    always_use_package_imports: false
    require_trailing_commas: false
    avoid_classes_with_only_static_members: false
    depend_on_referenced_packages: false
    avoid_dynamic_calls: false
analyzer:
  language:
    strict-casts: false
