name: statyx
description: State management with MVVM pattern
version: 0.1.0
homepage: https://github.com/elliotkhd/StatyX

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
